export enum EventType {
  CREATE,
  UPDATE
}

export enum ResponseHttp {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  DATABASE_ERROR = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500
}
